### ISSUE TITLE
About povray.3.7.0.rc3.withdepthmap

### ISSUE THREAD

**Issue by ryohachiuma** [ankurhanda/living_room_iclnuim#1]
Hi, thank you for ICL_NUIM dataset. 
I'm trying to generate a new sequence from dataset and povray script you provided ( such as https://www.doc.ic.ac.uk/~ahanda/VaFRIC/living_room.html).

I think the original povray does not generate a depth map, and you used "povray.3.7.0.rc3.withdepthmap" version. How can I find this version of povray ?

Thank you in advance!

**Comment by ankurhanda** [comment]
can you send me an email? I will share the link with you. My email address is here https://www.doc.ic.ac.uk/~ahanda/

**Comment by captain-pool** [comment]
Hey @ankurhanda I'm facing the same issue too. Dropping you an email. Can you please share that with me too?
Thanks!
